/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as OrderbookRouteImport } from './routes/orderbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBackendSplatRouteImport } from './routes/api/backend/$'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderbookRoute = OrderbookRouteImport.update({
  id: '/orderbook',
  path: '/orderbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendSplatRoute = ApiBackendSplatRouteImport.update({
  id: '/api/backend/$',
  path: '/api/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orderbook': typeof OrderbookRoute
  '/replay': typeof ReplayRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orderbook': typeof OrderbookRoute
  '/replay': typeof ReplayRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orderbook': typeof OrderbookRoute
  '/replay': typeof ReplayRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orderbook'
    | '/replay'
    | '/upload'
    | '/validation'
    | '/api/backend/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orderbook'
    | '/replay'
    | '/upload'
    | '/validation'
    | '/api/backend/$'
  id:
    | '__root__'
    | '/'
    | '/orderbook'
    | '/replay'
    | '/upload'
    | '/validation'
    | '/api/backend/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderbookRoute: typeof OrderbookRoute
  ReplayRoute: typeof ReplayRoute
  UploadRoute: typeof UploadRoute
  ValidationRoute: typeof ValidationRoute
  ApiBackendSplatRoute: typeof ApiBackendSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orderbook': {
      id: '/orderbook'
      path: '/orderbook'
      fullPath: '/orderbook'
      preLoaderRoute: typeof OrderbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/$': {
      id: '/api/backend/$'
      path: '/api/backend/$'
      fullPath: '/api/backend/$'
      preLoaderRoute: typeof ApiBackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderbookRoute: OrderbookRoute,
  ReplayRoute: ReplayRoute,
  UploadRoute: UploadRoute,
  ValidationRoute: ValidationRoute,
  ApiBackendSplatRoute: ApiBackendSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
