"""The bundled demo dataset (compatibility shim).

The canonical, deterministic generation now lives in the dataset registry
(``quantstream_dataset_registry.generate``), which is the single source of truth for
the official reproducibility dataset. This module re-exports the trade generators so
existing imports keep working, and still exposes the bundled sample CSV path.

The demo CLI itself loads from the checksummed dataset under ``data/demo`` (fetched
or regenerated by the registry), not from these in-process generators.
"""

from __future__ import annotations

from importlib.resources import files

from quantstream_dataset_registry.generate import (
    SAMPLE_SEED,
    SAMPLE_SYMBOL,
    injected_spike_count,
    sample_events,
    sample_prices,
)

__all__ = [
    "SAMPLE_SEED",
    "SAMPLE_SYMBOL",
    "injected_spike_count",
    "sample_events",
    "sample_prices",
    "sample_csv_path",
]


def sample_csv_path() -> str:
    """Path to the bundled sample CSV (the same data as sample_events)."""
    return str(files("quantstream_demo").joinpath("data/acme_trades.csv"))
